### PR TITLE
Implement some 46, 47 ops for parsing ints

### PR DESCRIPTION
**Pull request by phire**
This is enough to get pass the DISK= prompt in LOAD

### CODE REVIEW

**Comment by phire** [comment]
@EtchedPixels Can we get this merged?

**Comment by EtchedPixels** [comment]
I don't really want code in the actual tree proper which looks like it silently breaks on > 64bit and some similar cases.

**Comment by phire** [comment]
For `bignum_sub`, only the debug printf (which is commented out) breaks for numbers larger than 64bit.  
 `a_big`, `b_big` and `result_big` are not used for the emulated result. 

For ascii-to-int, I plan to eventually rewrite this to use dibble-dabble algorithm, which is probably what the microcode uses. Until then, it does do an error printf and exit. Is this acceptable?

**Comment by EtchedPixels** [comment]
ok

**Pull request merged**
